In [ ]:
import pandas as pd
import numpy as np

import itertools

In [ ]:
#@title Default title text


inFileName = "" #@param {type:"string"}

In [ ]:
#@title Default title text


outFileName = "" #@param {type:"string"}

In [ ]:
#inFileName = 'Book2.csv'
colnames=['Identifier', 'Formula	Calc Val',	'Override Val',	'Description',	'UOM', 'Override Lo Lim',	'Override Hi Lim',	'Verify']


inDf = pd.read_csv(inFileName, names=colnames, header=None) #this is for Appendix D Sheet

In [ ]:
inDf

,Identifier,Formula,Calc Val,Override Val,Description,UOM,Override Lo Lim,Override Hi Lim,Verify
0,AC7BIO1:BIO_500L_RCP_BASE1.F_0,1,1,NaN,POST-PROD ENABLE pH 0=NO 1=YES P54221R01_PH_EN...,NaN,UNRESTRICTED,UNRESTRICTED,ON
1,AC7BIO1:BIO_500L_RCP_BASE1.F_1,5.5,5.5,NaN,INITIAL PRE-PRODUCTION PRESSURE SETPOINT P5422...,PSIG,UNRESTRICTED,UNRESTRICTED,ON
2,AC7BIO1:BIO_500L_RCP_BASE1.F_2,25,25,NaN,INITIAL OVERLAY GAS FLOW SETPOINT P54221R01_OV...,SLPM,UNRESTRICTED,UNRESTRICTED,ON
3,AC7BIO1:BIO_500L_RCP_BASE1.F_3,5.5,5.5,NaN,PRE-MEDIA HOLD PRESSURE SETPOINT P54221R01_PRO...,PSIG,UNRESTRICTED,UNRESTRICTED,ON
4,AC7BIO1:BIO_500L_RCP_BASE1.F_4,20,20,NaN,PRE-MEDIA HOLD TEMPERATURE SETPOINT P54221R01_...,degC,UNRESTRICTED,UNRESTRICTED,ON
...,...,...,...,...,...,...,...,...,...
122,AC7BIO1:BIO_500L_RCP_BASE1.F_260,20,20,NaN,54221 APR OVERLAY FLOW LO LO ALARM SP1,SLPM,UNRESTRICTED,UNRESTRICTED,ON
123,AC7BIO1:BIO_500L_RCP_BASE1.F_261,"-99,999","-99,999",NaN,54221 APR OVERLAY FLOW LO ALARM SP1,SLPM,UNRESTRICTED,UNRESTRICTED,ON
124,AC7BIO1:BIO_500L_RCP_BASE1.F_262,"99,999","99,999",NaN,54221 APR OVERLAY FLOW HI ALARM SP1,SLPM,UNRESTRICTED,UNRESTRICTED,ON
125,AC7BIO1:BIO_500L_RCP_BASE1.F_263,30,30,NaN,54221 APR OVERLAY FLOW HI HI ALARM SP1,SLPM,UNRESTRICTED,UNRESTRICTED,ON
126,AC7BIO1:BIO_500L_RCP_BASE1.F_499,3,3,NaN,54221 CAMPAIGN ID,ID,UNRESTRICTED,UNRESTRICTED,ON

In [ ]:
currIndex = 0
ids = []
forms = []
calcs = []
ovrs = []
descs= []
uns = []
lolims = []
hilims = []
vers = []
regs = []

for count, (id, form, calc, ovr, desc, un, lolim, hilim, ver) in enumerate(zip(inDf['Identifier'],
                                                                               inDf['Formula'],inDf['Calc Val'],inDf['Override Val'],inDf['Description'],
                                                                               inDf['UOM'],inDf['Override Lo Lim'],inDf['Override Hi Lim'],inDf['Verify'])):

    #print(currIndex)

    if currIndex == int(str(id)[str(id).find('F_')+2:]):

        ids.append(id)
        forms.append(form)
        calcs.append(calc)
        ovrs.append(ovr)
        if currIndex < 100:
            descs.append(str(desc[:desc.rindex(' ')] + '(' + desc[desc.rindex(' ')+1:] + ')'))
        else:
            descs.append(str(desc))
        uns.append(un)
        lolims.append(lolim)
        hilims.append(hilim)
        vers.append(ver)

        regs.append('F95[' + str(currIndex) + ']')
        currIndex += 1

    else:

        while currIndex <= int(str(id)[str(id).find('F_')+2:]):

            #print(currIndex, str(id)[:str(id).find('F_')+2] + str(currIndex))
            if currIndex == int(str(id)[str(id).find('F_')+2:]):
                ids.append(id)
                forms.append(form)
                calcs.append(calc)
                ovrs.append(ovr)
                if currIndex < 100:
                    descs.append(str(desc[:desc.rindex(' ')] + '(' + desc[desc.rindex(' ')+1:] + ')'))
                else:
                    descs.append(str(desc))
                uns.append(un)
                lolims.append(lolim)
                hilims.append(hilim)
                vers.append(ver)

                regs.append('F95[' + str(currIndex) + ']')
                currIndex += 1

            else:
                ids.append(str(id)[:str(id).find('F_')+2] + str(currIndex))
                forms.append('0')
                calcs.append('0')
                ovrs.append('')
                descs.append(str(id)[:str(id).find('F_')+2] + str(currIndex))
                uns.append('')
                lolims.append('UNRESTRICTED')
                hilims.append('UNRESTRICTED')
                vers.append('ON')

                currIndex += 1

In [ ]:
for reg in regs:
    print(reg)

F95[0]
F95[1]
F95[2]
F95[3]
F95[4]
F95[5]
F95[6]
F95[7]
F95[8]
F95[9]
F95[10]
F95[11]
F95[12]
F95[13]
F95[14]
F95[15]
F95[16]
F95[17]
F95[18]
F95[19]
F95[20]
F95[21]
F95[22]
F95[23]
F95[24]
F95[25]
F95[26]
F95[27]
F95[28]
F95[29]
F95[30]
F95[31]
F95[32]
F95[33]
F95[34]
F95[35]
F95[38]
F95[39]
F95[40]
F95[41]
F95[42]
F95[43]
F95[44]
F95[45]
F95[46]
F95[47]
F95[48]
F95[49]
F95[50]
F95[51]
F95[52]
F95[53]
F95[54]
F95[55]
F95[56]
F95[57]
F95[58]
F95[59]
F95[60]
F95[61]
F95[201]
F95[202]
F95[203]
F95[204]
F95[205]
F95[206]
F95[207]
F95[208]
F95[209]
F95[210]
F95[211]
F95[212]
F95[213]
F95[214]
F95[215]
F95[216]
F95[217]
F95[218]
F95[219]
F95[220]
F95[221]
F95[222]
F95[223]
F95[224]
F95[225]
F95[226]
F95[227]
F95[228]
F95[229]
F95[230]
F95[231]
F95[232]
F95[233]
F95[234]
F95[235]
F95[236]
F95[237]
F95[238]
F95[239]
F95[240]
F95[241]
F95[242]
F95[243]
F95[244]
F95[245]
F95[246]
F95[247]
F95[248]
F95[249]
F95[250]
F95[251]
F95[252]
F95[253]
F95[254]
F95[255]
F95[256]
F95[257]
F95[258]
F95[259]
F95[260]
F95[261]
F95[262]
F95[263]

In [ ]:
outDf = pd.DataFrame()

outDf['Identifier '] = ids
outDf['Formula'] = forms
outDf['Calc Val'] = calcs
outDf['Override Val'] = ovrs
outDf['Description'] = descs
outDf['UOM'] = uns
outDf['Override Lo Lim'] = lolims
outDf['Override Hi Lim'] = hilims
outDf['Verify'] = vers

In [ ]:
outDf

,Identifier,Formula,Calc Val,Override Val,Description,UOM,Override Lo Lim,Override Hi Lim,Verify
0,AC7BIO1:BIO_500L_RCP_BASE1.F_0,1,1,NaN,POST-PROD ENABLE pH 0=NO 1=YES(P54221R01_PH_EN...,NaN,UNRESTRICTED,UNRESTRICTED,ON
1,AC7BIO1:BIO_500L_RCP_BASE1.F_1,5.5,5.5,NaN,INITIAL PRE-PRODUCTION PRESSURE SETPOINT(P5422...,PSIG,UNRESTRICTED,UNRESTRICTED,ON
2,AC7BIO1:BIO_500L_RCP_BASE1.F_2,25,25,NaN,INITIAL OVERLAY GAS FLOW SETPOINT(P54221R01_OV...,SLPM,UNRESTRICTED,UNRESTRICTED,ON
3,AC7BIO1:BIO_500L_RCP_BASE1.F_3,5.5,5.5,NaN,PRE-MEDIA HOLD PRESSURE SETPOINT(P54221R01_PRO...,PSIG,UNRESTRICTED,UNRESTRICTED,ON
4,AC7BIO1:BIO_500L_RCP_BASE1.F_4,20,20,NaN,PRE-MEDIA HOLD TEMPERATURE SETPOINT(P54221R01_...,degC,UNRESTRICTED,UNRESTRICTED,ON
...,...,...,...,...,...,...,...,...,...
495,AC7BIO1:BIO_500L_RCP_BASE1.F_495,0,0,,AC7BIO1:BIO_500L_RCP_BASE1.F_495,,UNRESTRICTED,UNRESTRICTED,ON
496,AC7BIO1:BIO_500L_RCP_BASE1.F_496,0,0,,AC7BIO1:BIO_500L_RCP_BASE1.F_496,,UNRESTRICTED,UNRESTRICTED,ON
497,AC7BIO1:BIO_500L_RCP_BASE1.F_497,0,0,,AC7BIO1:BIO_500L_RCP_BASE1.F_497,,UNRESTRICTED,UNRESTRICTED,ON
498,AC7BIO1:BIO_500L_RCP_BASE1.F_498,0,0,,AC7BIO1:BIO_500L_RCP_BASE1.F_498,,UNRESTRICTED,UNRESTRICTED,ON
499,AC7BIO1:BIO_500L_RCP_BASE1.F_499,0,0,,AC7BIO1:BIO_500L_RCP_BASE1.F_499,,UNRESTRICTED,UNRESTRICTED,ON

In [ ]:
outDf.to_csv(outFileName, index = False)